# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Gradle JVM
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# KMP / Compose
kotlin.mpp.enableCInteropCommonization=true

# WasmJs - use local Node.js
kotlin.wasm.nodeJsVersion=22.0.0
kotlin.wasm.nodeJsRoot=/home/artanniel/.nvm/versions/node/v20.19.5
kotlin.wasm.nodeJsDownload=false
kotlin.js.yarn=false
